### ISSUE TITLE
Add a "compact" preset

### ISSUE THREAD

**Issue by nojhan** [liquidprompt/liquidprompt-powerline#3]
The default theme adds spaces around Powerline's "arrows", which can lead to a very long prompt.

However, those spaces may be omitted without a big impact on readability.

Adding the option to have space or not (with default on having spaces) would then be a plus, in small terminals.

**Comment by Rycieos** [comment]
Isn't that as simple as setting `POWERLINE_SPACER=""`?

**Comment by nojhan** [comment]
That is true. My bad. I wrote that in a hurry, fearing to forget to check.
